eshop/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls import url



from eshop import views

app_name = "eshop_app"

urlpatterns = [
    path('', views.index, name="index"),
    path('secciones/', views.secciones, name="secciones"),
    path('producto/<int:id>/', views.producto, name="producto"),
    path('logout', LogoutView.as_view(), {"next_page": '/promociones/'}, name="logout"),
    path('signup/', views.signup.as_view(), name="signup"),
    path('update/<int:id>/<int:id2>/', views.update, name="update"),
    path('delete/<int:id>/<int:id2>/', views.delete, name="delete"),
    path('create/<int:id>/', views.create, name="create"),
    path('carrito/<int:id>/', views.carrito, name="carrito"),
    path('agregarcarrito/<int:id>/', views.agregarCarrito, name="agregarcarrito"),
    path('quitarcarrito/<int:id>/', views.quitarcarrito, name="quitarcarrito"),
    path('comprar/', views.comprar, name="comprar"),
    path('createCreditCard/', views.createCreditCard, name="createCreditCard"),
    path('deleteCC/<int:id>', views.deleteCC, name="deleteCC"),
    path('agregarproducto/', views.agregarproducto, name="agregarproducto"),
    path('agregarseccion/', views.agregarseccion, name="agregarseccion"),
    path('productoscomprados/', views.productoscomprados, name="productoscomprados"),
    path('success/', views.success, name="success"),
    path('CompraExitosa/', views.CompraExitosa, name="CompraExitosa"),
    url(r'^results/$', views.search, name='search'),
    
   # url(r'^create/(?P<param>\d+)/$', RedirectSomewhere.as_view(), name="create"),

    
]

proyecto2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#Empiezan Imagenes
##### NO SE PORQUE NO FUNCIONA ####### from . import views, settings
from eshop import views
from proyecto2 import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("eshop.urls", namespace="eshop_app")),
]

 
 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop/forms.py
from django import forms
from .models import Producto, Comment, CreditCard, seccion#, SeccionProducto

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator


STAR = (('1',1),('2',2),('3',3),('4',4),('5',5))

class FormComment(forms.ModelForm):
	Comentar = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}))
	estrellas = forms.ChoiceField(choices=STAR)
	class Meta:
		model = Comment
		fields = [
			"Comentar",
			"estrellas"
		]

class FormProducto(forms.ModelForm):
	name = forms.CharField(widget=forms.TextInput(attrs={"class": "form form-control"}))
	content = forms.CharField(widget=forms.TextInput(attrs={"class": "form form-control"}))
	precio = forms.CharField(widget=forms.TextInput(attrs={"class": "form form-control"}))
	seccion = forms.ModelChoiceField(widget=forms.Select, queryset = seccion.objects.all())
	photo = forms.ImageField()
	class Meta:
		model = Producto
		fields = [
			"name",
			"content",
			"precio",
			"seccion",
			"photo",

		]

class FormSeccion(forms.ModelForm):
	seccion = forms.CharField(widget=forms.TextInput(attrs={"class": "form form-control"}))
	
	class Meta:
		model = seccion
		fields = [
			"seccion",


		]

#class FormSeccionProducto(forms.ModelForm):
#	product = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset = Producto.objects.all())
#	seccion = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset = seccion.objects.all())
#	
#	class Meta:
#		model = SeccionProducto
#		fields = [
#			"product",
#			"seccion"
#
#
#		]


class FormProductoCarrito(forms.ModelForm):
	carritochecker = forms.BooleanField()
	class Meta:
		model = Producto
		fields = [
			"carritochecker",

		]

class FormProductoPurchased(forms.ModelForm):
	purchased = forms.BooleanField()
	class Meta:
		model = Producto
		fields = [
			"purchased",

		]

class FormCreditCard(forms.ModelForm):
	Numero_De_Tarjeta = 0
	Mes = 0
	Año = 0
	CVV = 0
	class Meta:
		model = CreditCard
		fields = [
			"CardNumber",
			"Month",
			"Year",
			"cvv"
		]
	


class LoginForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'size':30}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'size':30}))

class SignupForm(UserCreationForm):
	first_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form form-control"}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form form-control"}))
	email = forms.CharField(widget=forms.TextInput(attrs={"class": "form form-control"}))
	username = forms.CharField(widget=forms.TextInput(attrs={"class": "form form-control"}))
	password1 = forms.CharField(widget=forms.TextInput(attrs={"class": "form form-control"}))
	password2 = forms.CharField(widget=forms.TextInput(attrs={"class": "form form-control"}))

	class Meta:
		model = User
		fields = [
			"first_name",
			"last_name",
			"email",
			"username",
			"password1",
			"password2"
		]

eshop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.urls import reverse_lazy
from .models import  Producto, Counter, Comment, CreditCard, seccion, historialcompras, PromEst
from django.views.generic.base import RedirectView
from django.db.models import Sum, Q, Avg
from django.views.generic import TemplateView
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core.mail import EmailMessage
import random
#from example.config import pagination


from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from .forms import FormComment, LoginForm, SignupForm,  FormCreditCard, FormSeccion, FormProductoCarrito, FormProductoPurchased, FormProducto

queryCONTADORCARRITO = Producto.objects.filter(carritochecker=True)
lol = queryCONTADORCARRITO.count()

# Create your views here.
def index(request):
	#promestrellas = Comment.objects.filter(producto=producto)

	stars = PromEst.objects.all()
	lol = 0
	queryCONTADORCARRITO = Producto.objects.filter(carritochecker=True)
	lol = queryCONTADORCARRITO.count()
	message = "Not Logged yet"
	querysetIndex = Producto.objects.all()
	form = LoginForm(request.POST or None)
	if request.method == "POST":
		if form.is_valid():
			#data = form.cleaned_data
			#print(data)
			username = request.POST["username"]
			password = request.POST["password"]
			user = authenticate(username=username, password=password)
			#print(username)
			#print(password)
			if user is not None:
				if user.is_active:
					login(request, user)
					message = "User Logged"
				else:
					message = "User Not Active"
			else:
				message = "Username or password is not Correct"
		context = {
			"message": message,
			"form": form,
			"username": username,
			"objects": querysetIndex,
			"lol":lol,
			"stars":stars,
		}
	context = {
		"form": form,
		"lol":lol,
		"message": message,
		"objects": querysetIndex,
		"stars":stars,
	}
	return render(request, "eshop/index.html", context)

def secciones(request):
	lol = 0
	queryCONTADORCARRITO = Producto.objects.filter(carritochecker=True)
	lol = queryCONTADORCARRITO.count()

	prd = seccion.objects.all()
	
	context = {
		"lol":lol,
		"stars":prd,
		
	}
	return render(request, "eshop/secciones.html", context)






#	context = {
#		"lol":lol,
#		"prom":prom,
#		
#	}
#	return render(request, "eshop/index.html", context)

def producto(request, id):
	lol = 0
	queryCONTADORCARRITO = Producto.objects.filter(carritochecker=True)
	lol = queryCONTADORCARRITO.count()
	clave = id
	querysetComments = Comment.objects.filter(producto=id)
	queryset = Producto.objects.filter(id=id)
	validator = Producto.objects.get(id=id)

	var_title = queryset[0]
	counter = Counter
	form = FormComment()
	form2 = FormProductoCarrito()
	us = request.user
	sec = Producto.objects.all()
	flag = False
	if validator.carritochecker:
		flag = True

	context = {
	"objects": queryset,
	"lol":lol,
	"counter": counter,
	"title": var_title,
	"querysetComments": querysetComments,
	"create_form": FormComment(),
	"create_url": reverse_lazy("eshop_app:create",kwargs={'id': id},current_app='eshop'),
	"clave": clave,
	"carrito_form": form2,
	"carrito_url": reverse_lazy("eshop_app:agregarcarrito",kwargs={'id': id},current_app='eshop'),
	"sec":sec,
	"us":us,
	"flag":flag,
	"validator":validator

	}
	return render(request, "eshop/producto.html", context)

def carrito(request, id):
	message = "No hay productos en el carrito."
	flag = False
	queryTitle = Producto.objects.filter(id=id)
	queryPRODUCTOS = Producto.objects.filter(carritochecker=True)
	lol = queryPRODUCTOS.count()
	if lol > 1:
		message = " Productos en el carrito"
		Flag = True
	elif lol == 1:
		message = " Producto en el carrito"
		Flag = True
	else:
		message = message
		Flag = False
	#var_title = queryTitle[0]
	form = FormProductoCarrito()
	
	#form.fields["producto"].initial = Producto.objects.get(id=id)
	if form.is_valid():
		#Comment = form.save(commit=False)
		#form.fields.cleaned_data['producto'] = 2
		instance = form.save(commit=False)
		instance.carritochecker = True
		instance.save()
	context = {
		"productoID":id,
		"queryPRODUCTOS": queryPRODUCTOS,
		#"title": var_title,
		"message":message,
		"Flag":Flag,
		"lol":lol
	}
	return render(request, "eshop/carrito.html", context)

def comprar(request):
	lol = 0
	queryCONTADORCARRITO = Producto.objects.filter(carritochecker=True)
	lol = queryCONTADORCARRITO.count()
	queryPRODUCTOS = Producto.objects.filter(carritochecker=True)
	total = 0
	flag = False
	form = FormCreditCard()
	queryCARD = CreditCard.objects.filter(user=request.user)
	if queryCARD.count() > 0:
		flag = True
	else:
		flag = False
	prpchased = FormProductoPurchased()
	#for x in var_title:
	#	lol += var_title.precio
	total = Producto.objects.filter(carritochecker=True).aggregate(Sum('precio'))['precio__sum']
	context = {
		#"productoID":id,
		"queryPRODUCTOS": queryPRODUCTOS,
		"lol":lol,
		"form":form,
		"create_url": reverse_lazy("eshop_app:createCreditCard",current_app='eshop'),
		"CreditCard_form": form,
		"queryCARD":queryCARD,
		"flag":flag,
		"total":total,
		"purchased_form": prpchased,
		"carrito_url":reverse_lazy("eshop_app:success",current_app='eshop'),
	}
	return render(request, "eshop/comprar.html", context)
#Signup View
class signup(generic.CreateView):
	lol = 0
	queryCONTADORCARRITO = Producto.objects.filter(carritochecker=True)
	lol = queryCONTADORCARRITO.count()
	template_name = "eshop/signup.html"
	model = User
	form_class = SignupForm
	success_url = reverse_lazy("eshop_app:index")

def delete(request, id, id2):
	lol = 0
	queryCONTADORCARRITO = Producto.objects.filter(carritochecker=True)
	lol = queryCONTADORCARRITO.count()
	queryComment = Comment.objects.get(id=id)
	if request.method=="POST":
		queryComment.delete()

		#avg en productos
		prds = Producto.objects.all()
		res = 0
		for obj in prds:
			p = Producto.objects.get(id=obj.id)
			open = Comment.objects.filter(producto=obj.id)
			if open.count() == 0:
				res = 1
				d = PromEst.objects.filter(producto=p)
				if d.count() > 0:
					d.delete()
				avg = PromEst.objects.create(producto=p, calificacion=res)
				avg.save()
			else:
				res = Comment.objects.filter(producto=obj.id).aggregate(Avg('estrellas'))['estrellas__avg']
				d = PromEst.objects.filter(producto=p)
				if d.count() > 0:
					d.delete()
				avg = PromEst.objects.create(producto=p, calificacion=res)
				avg.save()

		return redirect("eshop_app:producto",id2)
	context = {
		#"form": form,
		"tweet": queryComment,
		"lol":lol,
		"id2":id2

	}
	return render(request, "eshop/delete.html", context)

def deleteCC(request, id):
	lol = 0
	queryCONTADORCARRITO = Producto.objects.filter(carritochecker=True)
	lol = queryCONTADORCARRITO.count()
	queryCC = CreditCard.objects.get(id=id)
	if request.method=="POST":
		queryCC.delete()
		return redirect("eshop_app:comprar")
	context = {
		#"form": form,
		"queryCC": queryCC,
		"lol":lol

	}
	return render(request, "eshop/deleteCC.html", context)

def update(request, id, id2):
	lol = 0
	queryCONTADORCARRITO = Producto.objects.filter(carritochecker=True)
	lol = queryCONTADORCARRITO.count()
	redir = id2
	object_tweet = Comment.objects.get(id=id)
	if request.method == "GET":
		form = FormComment(instance=object_tweet)
	else:
		form = FormComment(request.POST, instance=object_tweet)
		if form.is_valid():

			#avg en productos
			prds = Producto.objects.all()
			res = 0
			for obj in prds:
				p = Producto.objects.get(id=obj.id)
				open = Comment.objects.filter(producto=obj.id)
				if open.count() == 0:
					res = 1
					d = PromEst.objects.filter(producto=p)
					if d.count() > 0:
						d.delete()
					avg = PromEst.objects.create(producto=p, calificacion=res)
					avg.save()
				else:
					res = Comment.objects.filter(producto=obj.id).aggregate(Avg('estrellas'))['estrellas__avg']
					d = PromEst.objects.filter(producto=p)
					if d.count() > 0:
						d.delete()
					avg = PromEst.objects.create(producto=p, calificacion=res)
					avg.save()

			form.save()
		return redirect("eshop_app:producto",redir)
	context = {
		"form": form,
		"lol":lol
	}
	return render(request, "eshop/update.html", context)

def create(request, id):
	lol = 0
	queryCONTADORCARRITO = Producto.objects.filter(carritochecker=True)
	lol = queryCONTADORCARRITO.count()



	form = FormComment(request.POST or None)
	#form.fields["producto"].initial = Producto.objects.get(id=id)
	if form.is_valid():
		#Comment = form.save(commit=False)
		#form.fields.cleaned_data['producto'] = 2
		instance = form.save(commit=False)
		instance.user = request.user
		instance.producto = id
		instance.save()

		#avg en productos
		prds = Producto.objects.all()
		res = 0
		for obj in prds:
			p = Producto.objects.get(id=obj.id)
			open = Comment.objects.filter(producto=obj.id)
			if open.count() == 0:
				res = 1
				d = PromEst.objects.filter(producto=p)
				if d.count() > 0:
					d.delete()
				avg = PromEst.objects.create(producto=p, calificacion=res)
				avg.save()
			else:
				res = Comment.objects.filter(producto=obj.id).aggregate(Avg('estrellas'))['estrellas__avg']
				d = PromEst.objects.filter(producto=p)
				if d.count() > 0:
					d.delete()
				avg = PromEst.objects.create(producto=p, calificacion=res)
				avg.save()

		return redirect('eshop_app:producto',id)
		#return reverse_lazy('eshop_app:producto',kwargs={'id': 2},current_app='eshop')
	else:
		form = FormComment()
		context = {
			"form": form,
			"lol":lol
		}
		return render(request, "eshop/create.html", context)

#def agregarCarrito(request, id):
#	obj = Producto.objects.get(id=id)
#	carrito
#		return render(request, "eshop/agregarcarrito.html", context)

def agregarCarrito(request, id):
	lol = 0
	queryCONTADORCARRITO = Producto.objects.filter(carritochecker=True)
	lol = queryCONTADORCARRITO.count()
	open = Producto.objects.get(id=id)
	open.carritochecker = True
	open.save()
	return redirect("eshop_app:carrito",id)

templates/eshop/agregarcarrito.html
hola

templates/eshop/agregarproducto.html
{% extends "base.html" %}
{% block title %}CrearProducto{% endblock %}

{% block content %}
<div>
	<form method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form.as_p }}
			<br>
			<button type="submit" class="btn btn-primary" >Crear Producto</button>

	</form>
	</div>
{% endblock %}

templates/eshop/carrito.html
{% extends "base.html" %}
{% block title %}Agregar al carrito{% endblock %}

{% block content %}


{% if Flag %}
<table class="table table-stripped">
	<th class="table-primary"><center><h4><strong>Nombre</strong></h4></center></th>
	<th class="table-primary"><h4><strong>Descripcion</strong></h4></th>
	<th class="table-primary"><center><h4><strong>Precio</strong></h4></center></th>
	<th class="table-primary"><center><h4><strong>Imagen</strong></h4></center></th>
	<th class="table-primary"><center><strong><h4>Accion</h4></strong></center></th>
	{% for producto in queryPRODUCTOS %}
		<tr>
			<td><center><h3>{{ producto.name }}</h3></center></td>
			<td><h4>{{ producto.content }}</h4></td>
			<td><center><h2>${{ producto.precio }} Dlls</h2></center></td>
			<td><center><img src="{{ producto.photo.url }}" width="200" height="200" alt="{{ producto.name }}"></center></td>
			<td><center><h4><p><a href="{% url 'eshop_app:quitarcarrito' producto.id %}">Quitar del Carrito</a></p></h4></center></td>


		</tr>


	{% endfor %}


</table>
<br>
<div>
<h3 style="text-align:right;">{{lol}} {{message}} &nbsp;&nbsp; </h3>
&nbsp;&nbsp;<a href="{% url 'eshop_app:index'%}" class="btn btn-primary">Seguir Comprando</a>&nbsp;&nbsp;
{% if request.user.is_authenticated %}
<a href="{% url 'eshop_app:comprar' %}" class="btn btn-success">Proceder a compra</a>
{% else %}
<br>
<h3>Debe iniciar sesion antes de proceder con su compra.</h3>
{% endif %}
</div>
<br>
<br>



	



{% else %}
<center>
	<br>
	<br>
	<br>
	<br>
	<h1>{{message}}</h1>
</center>
	
{% endif %}

<table class="table table-stripped">
		<th class="table-dark">&nbsp;</th>
	</table>
{% endblock %}

templates/eshop/comprar.html
{% extends "base.html" %}
{% block title %}Pagar{% endblock %}

{% block content %}

{% if flag == True%}
	

	<table class="table table-striped table-bordered table-sm">
	<th class="table-primary">Usuario</th>
	<th class="table-primary">Numero de Tarjeta</th>
	<th class="table-primary">Accion</th>
	<th class="table-primary"></th>
	{% for producto in queryCARD %}
		<tr >
			<td class="table-dark">{{ producto.user }}</td>
			<td class="table-dark">{{ producto.CardNumber }}</td>
			<td class="table-dark"><p><a href="{% url 'eshop_app:deleteCC' producto.id %}" class="btn btn-primary">Borrar Tarjeta</a></p></td>
			<td class="table-warning"><center><img src="/media/proyecto/tarjeta.png" height="50" width="50"></center></td>
		</tr>
	{% endfor %}
</table>


{% else %}
	<center>
	<h4>Porfavor ingrese su Tarjeta</h4>
	{% include "eshop/form_CreditCard.html" with form=CreditCard_form action_url=create_url btn_title="Agregar Tarjeta"%}
	</center>
{% endif %}

<h1>Articulos a comprar:</h1>
	<table class="table table-stripped">
		<th><center><h4><strong>Nombre</strong></h4></center></th>
		<th><h4><strong>Descripcion</strong></h4></th>
		<th><center><h4><strong>Precio</strong></h4></center></th>
		<th><center><h4><strong>Imagen</strong></h4></center></th>
		{% for producto in queryPRODUCTOS %}
			<tr>
				<td><center><h3>{{ producto.name }}</h3></center></td>
				<td><h4>{{ producto.content }}</h4></td>
				<td><center><h2>${{ producto.precio }} Dlls</h2></center></td>
				<td><center><img src="{{ producto.photo.url }}" width="200" height="200" alt="{{ producto.name }}"></center></td>

			</tr>
		{% endfor %}
	</table>

<h1 style="text-align:right;">Total: {{total}}</h1>
&nbsp;&nbsp;<a href="{% url 'eshop_app:index'%}" class="btn btn-primary">Seguir Comprando</a>
{% if flag == True%}
	{% include "eshop/form_purchased.html" with form=purchased_form action_url=carrito_url btn_title="Agregar al carrito"%}
{% endif %}
<br>
<br>

<table class="table table-stripped">
		<th class="table-dark">&nbsp;</th>
	</table>

{% endblock %}

templates/eshop/createCreditCard.html
{% extends "base.html" %}
{% block title %}Add Credit Card{% endblock %}

{% block content %}
	<div>
		{% include "eshop/form_create.html" %}
	</div>
{% endblock %}

templates/eshop/delete.html
{% extends "base.html" %}
{% block title %}DeleteTweet{% endblock %}

{% block content %}
<center>
		<form method="POST">
			{% csrf_token %}
			<br>
			<h1>¿Realmente quieres Borrar este comentario?</h1>
			<h3>"{{ tweet.Comentar }}"</h3>
			<br>
			<button type="submit" class="btn btn-danger">&nbsp;&nbsp;&nbsp;&nbsp;Delete&nbsp;&nbsp;&nbsp;&nbsp;</button>&nbsp;
			<a href="{% url 'eshop_app:producto' id2 %}" class="btn btn-primary" type="button">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>

	</form>
</center>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

	<center><img src="/media/proyecto/alerta.png" width="200" height="200"></center>

	
{% endblock %}

templates/eshop/deleteCC.html
{% extends "base.html" %}
{% block title %}Delete Credit Card{% endblock %}

{% block content %}
<center>
		<form method="POST">
			{% csrf_token %}
			<br>
			<h1>¿Realmente quieres Borrar esta Tarjeta?</h1>
			<table class="table table-striped table-bordered table-sm">
				<th class="table-primary">Usuario</th>
				<th class="table-primary">Numero de Tarjeta</th>
				<th class="table-primary"></th>
					<tr >
						<td class="table-dark">{{ queryCC.user }}</td>
						<td class="table-dark">{{ queryCC.CardNumber }}</td>
						<td class="table-warning"><center><img src="/media/proyecto/tarjeta.png" height="50" width="50"></center></td>
					</tr>
			</table>

			<br>
			<button type="submit" class="btn btn-danger">&nbsp;&nbsp;&nbsp;&nbsp;Delete&nbsp;&nbsp;&nbsp;&nbsp;</button>&nbsp;
			<a href="{% url 'eshop_app:comprar' %}" class="btn btn-primary" type="button">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>

	</form>
</center>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

	<center><img src="/media/proyecto/alerta.png" width="200" height="200"></center>

	
{% endblock %}

templates/eshop/form_CreditCard.html
<form method="POST" action="{% if action_url %}{{ action_url }}{% endif %}">
				{% csrf_token %}
				{{ form }}
			
			<button type="submit" class="btn btn-primary">Agregar Tarjeta</button>

	</form>

templates/eshop/post_list.html
{% extends "base.html" %}
{% block title %}Add Credit Card{% endblock %}

{% block content %}
	<form method="GET" action="{% url 'eshop:search' %}">
				<input value="{{request.GET.q}}" name="q" placeholder="search...">
			
			<button type="submit" class="btn btn-success">search</button>

	</form>
{% endblock %}

templates/eshop/producto.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}

{% block content %}

<table class="table table-stripped table-bordered">
	<th class="table-primary"><center><h4><strong>Nombre</strong></h4></center></th>
	<th class="table-primary"><h4><strong>Descripcion</strong></h4></th>
	<th class="table-primary"><center><h4><strong>Precio</strong></h4></center></th>
	<th class="table-primary"><center><h4><strong>Imagen</strong></h4></center></th>
	{% for producto in objects %}
		<tr>
			<td><center><h3>{{ producto.name }}</h3></center></td>
			<td><h4>{{ producto.content }}</h4></td>
			<td><center><h2>${{ producto.precio }} Dlls</h2></center></td>
			<td><center><img src="{{ producto.photo.url }}" width="200" height="200" alt="{{ producto.name }}"></center></td>

		</tr>
	{% endfor %}

</table>



{% if flag == False %}
	<p><img src="/media/proyecto/carrito.jpg" width="50" height="50" alt="carrito" style="">{% include "eshop/form_carrito.html" with form=carrito_form action_url=carrito_url btn_title="Agregar al carrito"%}</p>
{% else %}
	<h4>Este producto ya esta en el carrito</h4>
	<a href="{% url 'eshop_app:carrito' validator.id %}" class="btn btn-primary">Ver en el carrito</a>
{% endif %}


	<div class="row">
		<ul id="wsTweets">
			
		</ul>

	</div>
	
	<br>
	<table class= "table table-condensed">
		<th class="table-warning"><center><strong><h5>Usuario</h5></strong></center></th>
		<th class="table-warning"><center><strong><h5>Comentario</h5></strong></center></th>
		<th class="table-warning"><center><strong><h5>Publicado</h5></strong></center></th>
		<th class="table-warning"><center><strong><h5>Acciones</h5></strong></center></th>
		<th class="table-warning"><center><strong><h5>---</h5></strong></center></th>
		<th class="table-warning"><center><strong><h5>Estrellas</h5></strong></center></th>

		{% for tweet in querysetComments %}
			<tr>
				<td><center>{{ tweet.user }}</center></td>
				<td><center>{{ tweet.Comentar }}</center></td>
				<td><center>{{ tweet.timestamp | timesince }} ago</center></td>
				{% if tweet.user == us %}<td><center><a href="{% url 'eshop_app:update' tweet.id tweet.producto %}" class="btn btn-link">Update</a></center></td>
				{% else %}
				<td></td>
				{% endif %}
				{% if tweet.user == us %}<td><center><p><a href="{% url 'eshop_app:delete' tweet.id tweet.producto %}">Delete</a></p></center></td>
				{% else %}
				<td></td>
				{% endif %}
				<td ><center><big style="vertical-align: text-top;"><strong>{{tweet.estrellas}}&nbsp;&nbsp;&nbsp;&nbsp;</strong></big><img style="text-align:left;" align="top" src="/media/proyecto/estrella1.jpg" height="25" width="25"></center></td>
			</tr>
		{% endfor %}
		
	</table>
	
	
	

	{% if request.user.is_authenticated %}
		{% include "eshop/form_create.html" with form=create_form action_url=create_url btn_title="Publicar"%}

	{% else %}
	<br>
		<center><h1>Porfavor Inicia sesion para comentar</h1></center>
	{% endif %}
{% endblock %}