eshop/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls import url



from eshop import views

app_name = "eshop_app"

urlpatterns = [
    path('', views.index, name="index"),
    path('secciones/', views.secciones, name="secciones"),
    path('producto/<int:id>/', views.producto, name="producto"),
    path('logout', LogoutView.as_view(), {"next_page": '/promociones/'}, name="logout"),
    path('signup/', views.signup.as_view(), name="signup"),
    path('update/<int:id>/<int:id2>/', views.update, name="update"),
    path('delete/<int:id>/<int:id2>/', views.delete, name="delete"),
    path('create/<int:id>/', views.create, name="create"),
    path('carrito/<int:id>/', views.carrito, name="carrito"),
    path('agregarcarrito/<int:id>/', views.agregarCarrito, name="agregarcarrito"),
    path('quitarcarrito/<int:id>/', views.quitarcarrito, name="quitarcarrito"),
    path('comprar/', views.comprar, name="comprar"),
    path('createCreditCard/', views.createCreditCard, name="createCreditCard"),
    path('deleteCC/<int:id>', views.deleteCC, name="deleteCC"),
    path('agregarproducto/', views.agregarproducto, name="agregarproducto"),
    path('agregarseccion/', views.agregarseccion, name="agregarseccion"),
    path('productoscomprados/', views.productoscomprados, name="productoscomprados"),
    path('success/', views.success, name="success"),
    path('CompraExitosa/', views.CompraExitosa, name="CompraExitosa"),
    url(r'^results/$', views.search, name='search'),
    
   # url(r'^create/(?P<param>\d+)/$', RedirectSomewhere.as_view(), name="create"),

    
]

proyecto2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#Empiezan Imagenes
##### NO SE PORQUE NO FUNCIONA ####### from . import views, settings
from eshop import views
from proyecto2 import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("eshop.urls", namespace="eshop_app")),
]

 
 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
  <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
  <link rel="stylesheet" href="{% static 'static/css/proyecto.css' %}">

	<title>{% block title%}{% endblock %}</title>

{%include 'navbar.html' %}



{% block content %}

{% endblock %}





<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>





	{% block script %} {% endblock %}

  <script type="text/javascript" src="{% static 'bootstrap/dist/js/jquery.js' %}"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'eshop_app:index' %}">E-Shop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'eshop_app:index' %}">Inicio <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'eshop_app:secciones' %}">Secciones</a>
      </li>
      {% if user.is_superuser%}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Herramientas Admin
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'eshop_app:agregarproducto' %}">Agregar Producto</a>
          <a class="dropdown-item" href="{% url 'eshop_app:agregarseccion' %}">Agregar Seccion</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Proximamente mas opciones</a>
        </div>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'eshop_app:productoscomprados' %}">Historial de Compras</a>
      </li>
      <!--
      {% if user.is_superuser%}
      <li class="nav-item">
        <a class="btn btn-link" href="{% url 'eshop_app:agregarproducto' %}">Agregar Producto</a>
      </li>
      <li class="nav-item">
        <a class="btn btn-link" href="{% url 'eshop_app:agregarseccion' %}">Agregar Seccion</a>
      </li>
      {% else %}
      {% endif %}
    -->

    </ul>
    <form class="form-inline my-2 my-lg-0" role="search" method="GET" action="{% url 'eshop_app:search' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" value="{{request.GET.q}}" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>&nbsp;&nbsp;
      {% if request.user.is_authenticated %}
      &nbsp;&nbsp;&nbsp;&nbsp;Signed as {{ request.user }}&nbsp;&nbsp; <br>
      	{% if lol > 0 %}
      		<a  href="{% url 'eshop_app:carrito' 1 %}" class="btn btn-primary"> "{{lol}}" en Carrito</a>&nbsp;&nbsp;
     	 {% else %}
     	 	<a  href="{% url 'eshop_app:carrito' 1 %}" class="btn btn-primary">Carrito</a>&nbsp;&nbsp;
     	 {% endif %}
      <a href="{% url 'eshop_app:logout' %}?next=/" class="btn btn-info">Logout</a>
    {% else %}
    <a  href="{% url 'eshop_app:carrito' 1 %}" class="btn btn-primary">Carrito</a>&nbsp;&nbsp;
      <a href="{% url 'eshop_app:index' %}" class="btn btn-link">Login</a>
      or else
      <a href="{% url 'eshop_app:signup' %}" class="btn btn-link">Signup</a>
      
    {% endif %}
    

    </form>
  </div>
</nav>

</head>